# Generated by Django 2.0.1 on 2019-09-10 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oneguocity',
            name='is_hot',
            field=models.IntegerField(choices=[(0, '热门'), (1, '非热门')], default=1, max_length=10, verbose_name='是否热门'),
        ),
    ]
