# Generated by Django 2.0.1 on 2019-09-10 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userapp', '0001_initial'),
        ('goodsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneGuoComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(max_length=500, verbose_name='用户评论')),
            ],
            options={
                'verbose_name': '用户评论',
                'verbose_name_plural': '用户评论',
                'db_table': 'comments',
            },
        ),
        migrations.CreateModel(
            name='OrderDetailModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_goods_num', models.IntegerField(default=1, verbose_name='商品数量')),
                ('order_goods_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='goodsapp.GoodsModelEntity', verbose_name='商品ID')),
            ],
            options={
                'verbose_name': '订单详情',
                'verbose_name_plural': '订单详情',
                'db_table': 'OrderDetail',
            },
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('order_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='订单ID')),
                ('order_price', models.FloatField(verbose_name='总价格')),
                ('order_time', models.DateTimeField(auto_now=True, verbose_name='下单时间')),
                ('order_state', models.CharField(choices=[(0, '下单未付款'), (1, '待收货'), (2, '待评论')], default=0, max_length=100, verbose_name='订单状态')),
                ('address_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.OneGuoAddress', verbose_name='地址ID')),
                ('order_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.OneGuoUser', verbose_name='用户ID')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'db_table': 'Order',
            },
        ),
        migrations.AddField(
            model_name='orderdetailmodel',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orderapp.OrderModel', verbose_name='订单ID'),
        ),
        migrations.AddField(
            model_name='oneguocomment',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orderapp.OrderModel', verbose_name='订单ID'),
        ),
        migrations.AddField(
            model_name='oneguocomment',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.OneGuoUser', verbose_name='用户ID'),
        ),
    ]
