# Generated by Django 2.0.1 on 2019-09-10 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='order_state',
            field=models.CharField(choices=[('0', '下单未付款'), ('1', '待收货'), ('2', '待评论')], default=0, max_length=100, verbose_name='订单状态'),
        ),
    ]
