# Generated by Django 2.0.1 on 2019-09-09 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goodsapp', '0004_auto_20190909_1916'),
        ('orderapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetailmodel',
            name='order_goods_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='goodsapp.GoodsModelEntity', verbose_name='商品ID'),
        ),
    ]
