# Generated by Django 2.0.1 on 2019-09-10 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0002_auto_20190910_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='order_state',
            field=models.IntegerField(choices=[(0, '下单未付款'), (1, '待收货'), (2, '待评论')], default=0, verbose_name='订单状态'),
        ),
    ]
