# Generated by Django 2.0.1 on 2019-09-10 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0003_auto_20190910_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='order_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='订单ID'),
        ),
    ]
