<<<<<<< HEAD
# Generated by Django 2.0.1 on 2019-09-09 11:24

from django.db import migrations, models
import django.db.models.deletion
=======
# Generated by Django 2.0.1 on 2019-09-09 10:28

from django.db import migrations, models
>>>>>>> ccd5ad33554c515af07a39a225123d3c011d3b57


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Category',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='编码')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('grade', models.IntegerField(default=1, verbose_name='等级')),
                ('picture_url', models.CharField(blank=True, max_length=200, null=True, verbose_name='图片路径')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goodsapp.Category', verbose_name='父类')),
            ],
            options={
                'verbose_name': '分类表',
                'verbose_name_plural': '分类表',
                'db_table': 't_category',
            },
        ),
        migrations.CreateModel(
=======
>>>>>>> ccd5ad33554c515af07a39a225123d3c011d3b57
            name='Goods_cartModelEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='用户id')),
                ('goods_id', models.IntegerField(verbose_name='商品id')),
                ('goods_count', models.IntegerField(verbose_name='商品数量')),
                ('is_choice', models.BooleanField(choices=[(0, 'True'), (1, 'False')], verbose_name='是否选中')),
            ],
            options={
                'verbose_name': '购物车表',
                'verbose_name_plural': '购物车表',
                'db_table': 't_goods_cart',
            },
        ),
        migrations.CreateModel(
            name='GoodsModelEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_type', models.IntegerField(verbose_name='商品分类')),
                ('goods_type_info', models.CharField(max_length=20, verbose_name='分类详情')),
                ('goods_name', models.CharField(max_length=10, verbose_name='商品名称')),
                ('goods_info', models.CharField(max_length=50, verbose_name='商品描述')),
                ('goods_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='商品价格')),
                ('super_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='市场价格')),
                ('product_address', models.CharField(max_length=30, verbose_name='原产地')),
                ('info_page', models.ImageField(upload_to='goods', verbose_name='详情页图片')),
                ('goods_sale', models.IntegerField(verbose_name='销量')),
                ('goods_have', models.IntegerField(verbose_name='库存')),
                ('info_id', models.IntegerField(verbose_name='详情id')),
                ('type_id', models.IntegerField(verbose_name='分类id')),
                ('goods_img', models.ImageField(upload_to='goods', verbose_name='商品图片')),
                ('is_detail', models.BooleanField(choices=[(0, '是'), (1, '否')], verbose_name='是否精选图片')),
            ],
            options={
                'verbose_name': '商品表',
                'verbose_name_plural': '商品表',
                'db_table': 't_goods',
            },
        ),
    ]
