# Generated by Django 2.0.1 on 2019-09-09 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goodsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods_cartmodelentity',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.OneGuoUser', verbose_name='用户id'),
        ),
    ]
