# Generated by Django 2.0.1 on 2019-09-10 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsmodelentity',
            name='goods_img',
            field=models.ImageField(blank=True, null=True, upload_to='goods', verbose_name='商品图片'),
        ),
        migrations.AlterField(
            model_name='goodsmodelentity',
            name='info_page',
            field=models.ImageField(blank=True, null=True, upload_to='goods', verbose_name='详情页图片'),
        ),
    ]
