# Generated by Django 2.0.1 on 2019-09-09 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goodsapp', '0002_auto_20190909_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods_cartmodelentity',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userapp.OneGuoUser', verbose_name='用户id'),
        ),
    ]
