# Generated by Django 2.0.1 on 2019-09-09 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goodsapp', '0003_auto_20190909_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods_cartmodelentity',
            name='goods_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodsapp.GoodsModelEntity', verbose_name='商品id'),
        ),
    ]
